export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const CLEAR_SEARCH_VALUE = "CLEAR_SEARCH_VALUE";
export const SEARCH_BY_PRESS_ENTER_BUTTON = "SEARCH_BY_PRESS_ENTER_BUTTON";
export const SET_FILTERS = "SET_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
