const initialState = [
  {
    id: "1",
    orderDate: "15.02.2021, 18:00",
    orderStatus: "Новый",
    positionCount: "6",
    orderAmount: "101 907",
    customerName: "Чернышев Филипп Семёнович",
  },
  {
    id: "2",
    orderDate: "12.03.2021, 05:15",
    orderStatus: "Новый",
    positionCount: "2",
    orderAmount: "98 003",
    customerName: "Филиппов Степан Васильевич",
  },
  {
    id: "3",
    orderDate: "03.02.2021, 08:04",
    orderStatus: "Рассчет",
    positionCount: "5",
    orderAmount: "3 800",
    customerName: "Тихонова Алина Давидовна",
  },
  {
    id: "4",
    orderDate: "21.01.2021, 13:32",
    orderStatus: "Выполнен",
    positionCount: "1",
    orderAmount: "5 700",
    customerName: "Александрова Юлия Никитична",
  },
  {
    id: "5",
    orderDate: "19.01.2021, 10:28",
    orderStatus: "Отменен",
    positionCount: null,
    orderAmount: null,
    customerName: "Андрей",
  },
  {
    id: "6",
    orderDate: "04.01.2021, 12:12",
    orderStatus: "Отложен",
    positionCount: "1",
    orderAmount: "20 500",
    customerName: "Судакова Анастасия Ильинична",
  },
  {
    id: "7",
    orderDate: "17.12.2020, 22:45",
    orderStatus: "Выполнен",
    positionCount: "1",
    orderAmount: "1 399",
    customerName: "Зверева Арина Николаевна",
  },
  {
    id: "8",
    orderDate: "07.12.2020, 08:57",
    orderStatus: "Выполнен",
    positionCount: "3",
    orderAmount: "117 810",
    customerName: "Карташов Максим Кириллович",
  },
  {
    id: "9",
    orderDate: "15.11.2020, 14:26",
    orderStatus: "Выполнен",
    positionCount: "1",
    orderAmount: "17 008",
    customerName: "Васильев Вадим Данилович",
  },
  {
    id: "10",
    orderDate: "07.11.2020, 18:52",
    orderStatus: "Отменен",
    positionCount: null,
    orderAmount: null,
    customerName: "София",
  },
  {
    id: "11",
    orderDate: "05.02.2020, 11:00",
    orderStatus: "Выполнен",
    positionCount: "1",
    orderAmount: "10 907",
    customerName: "Чернышев Семён Семёнович",
  },
  {
    id: "12",
    orderDate: "21.01.2020, 12:04",
    orderStatus: "Выполнен",
    positionCount: "2",
    orderAmount: "9 088",
    customerName: "Иванов Иван Иванович",
  },
  {
    id: "13",
    orderDate: "15.01.2020, 16:00",
    orderStatus: "Выполнен",
    positionCount: "1",
    orderAmount: "1 007",
    customerName: "Петров Петр Петрович",
  },
  {
    id: "14",
    orderDate: "13.01.2020, 08:11",
    orderStatus: "Отменен",
    positionCount: null,
    orderAmount: null,
    customerName: "Иван",
  },
  {
    id: "15",
    orderDate: "12.01.2020, 14:14",
    orderStatus: "Отменен",
    positionCount: null,
    orderAmount: null,
    customerName: "Михаил",
  },
];

export const orderList = (state = initialState) => state;
